" Make Vim more useful
set nocompatible

" Make Vim XDG compliant
source $XDG_CONFIG_HOME/vim/xdg.vim

" Use the Solarized Dark theme
@REM set background=dark
@REM colorscheme solarized
@REM let g:solarized_termtrans=1

" Use Dracula theme
packadd! dracula
colorscheme dracula

" use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed

" Allow cursor keys in insert mode
set esckeys

" Allow backspace in insert mode
set backspace=indent,eol,start

" Enable line numbers
set number

" Enable syntax highlighting
syntax enable

" Highlight current line
set cursorline

" Show “invisible” characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" Highlight searches
set hlsearch

" Ignore case of searches
set ignorecase

" Highlight dynamically as pattern is typed
set incsearch

" Always show status line
set laststatus=2

" Enable mouse in all modes
set mouse=a

" Show the current mode
set showmode

" Show the filename in the window titlebar
set title
