#!/bin/sh

# Homebrew and homebrew packages

set -e

echo Running bootstrap file: "$(basename "$0")" >&2

# Disable shellchecks that complain about yadm templating
# shellcheck disable=SC1073,SC1054,SC1083,SC1009
# shellcheck disable=SC1056,SC1072

echo {{ yadm.os }}
echo {{ yadm.class }}

{% if yadm.os == "Darwin" %}
{% if yadm.class == "Tesst" %}

echo foo

{% else %}

echo bar

{% endif %}
{% endif %}
