#!/bin/sh

set -e

vscode_dir=~/Library/Application\ Support/Code/
if [ -f "$vscode_dir/settings.json" ] ; then
    echo "Backing up existing vscode user settings ..." >&2
    mv "$vscode_dir/settings.json" "$vscode_dir/settings.json.bak"
fi

echo "Linking vscode user settings ..." >&2
ln -fs "$XDG_CONFIG_HOME/vscode/settings.json" "$vscode_dir/User/settings.json"

echo "Installing vscode plugins ..." >&2